version: '3.8'

services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_build:/app/result_build/dist
    container_name: 'frontend'

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./gnezdokavkaza.crt:/etc/ssl/gnezdokavkaza.crt
      - ./gnezdokavkaza.key:/etc/ssl/gnezdokavkaza.key

    depends_on:
      - frontend
    container_name: 'nginx'

volumes:
  static_value:
  media_value:
  frontend_build:
