# Generated by Django 3.2 on 2022-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название партнера')),
                ('description', models.TextField(unique=True, verbose_name='Краткая информация о партнере')),
                ('image', models.ImageField(upload_to='partners_img/', verbose_name='Логотип партнера')),
                ('url', models.URLField(verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнера',
                'verbose_name_plural': 'Наши партнеры',
            },
        ),
        migrations.CreateModel(
            name='Principles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Описание принципа')),
                ('image', models.ImageField(upload_to='principles_img/', verbose_name='Картинка к принципу')),
            ],
            options={
                'verbose_name': 'Принцип',
                'verbose_name_plural': 'Наши принципы',
            },
        ),
        migrations.CreateModel(
            name='Requisites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(unique=True, verbose_name='Реквизиты органицации')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.AddConstraint(
            model_name='partners',
            constraint=models.UniqueConstraint(fields=('name', 'url'), name='unique_partners'),
        ),
    ]
