# Generated by Django 3.2.16 on 2022-11-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Причина')),
                ('beneficial_to', models.CharField(choices=[('CHILD', 'ребенку'), ('PARENT', 'родителям')], max_length=10, verbose_name='Кому понравится')),
                ('image', models.ImageField(blank=True, help_text='Можете добавить фотографию', null=True, upload_to='benefits/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Причина выбора курсов родителями / детьми',
                'verbose_name_plural': 'Причины выбора курсов родителями / детьми',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Введите имя, которое будет отображаться на сайте', max_length=100, unique=True, verbose_name='Имя участника команды')),
                ('role', models.CharField(max_length=100, verbose_name='Роль в команде')),
                ('image', models.ImageField(upload_to='team_members/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Участник команды',
                'verbose_name_plural': 'Участники команды',
                'ordering': ('name',),
            },
        ),
    ]
