# Generated by Django 2.2.28 on 2022-10-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнера', 'verbose_name_plural': 'Наши партнеры'},
        ),
        migrations.AlterModelOptions(
            name='principles',
            options={'verbose_name': 'Принцип', 'verbose_name_plural': 'Наши принципы'},
        ),
        migrations.AlterField(
            model_name='partners',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название партнера'),
        ),
        migrations.AlterField(
            model_name='partners',
            name='text',
            field=models.TextField(unique=True, verbose_name='Краткая информация о партнере'),
        ),
        migrations.AlterField(
            model_name='principles',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к принципу'),
        ),
    ]
