# Generated by Django 3.2 on 2022-10-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principles',
            name='image',
            field=models.ImageField(blank=True, upload_to='principles_img/', verbose_name='Картинка к принципу'),
        ),
    ]
