# Generated by Django 2.2.19 on 2022-10-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Вопросы', 'verbose_name_plural': 'Часто задаваемые вопросы'},
        ),
    ]
