# Generated by Django 2.2.28 on 2022-10-24 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0002_auto_20221021_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='partners',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='partners_img/', verbose_name='Логотип партнера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='principles',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='principles_img/', verbose_name='Картинка для принципа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='principles',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Дополнение к принципу'),
        ),
    ]
