# Generated by Django 3.2 on 2022-10-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0002_alter_principles_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisites',
            options={'verbose_name': 'Реквизиты', 'verbose_name_plural': 'Реквизиты организации'},
        ),
        migrations.AlterField(
            model_name='requisites',
            name='text',
            field=models.TextField(unique=True, verbose_name='Реквизиты организации'),
        ),
    ]
