# Generated by Django 2.2.19 on 2022-10-29 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('npo_project', '0003_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=50, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=50, verbose_name='Ответ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAQ', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
