# Generated by Django 2.2.28 on 2022-10-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0003_auto_20221024_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principles',
            name='image',
        ),
    ]
