# Generated by Django 2.2.19 on 2022-10-29 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0004_auto_20221029_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='author',
        ),
    ]
