# Generated by Django 2.2.19 on 2022-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npo_project', '0005_remove_faq_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.TextField(max_length=50, verbose_name='Адрес')),
                ('image', models.ImageField(upload_to='location_img/', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
