name: Stylelint

on:
  pull_request:
    branches: [ master, main, develop ]
  push:
    branches: [ master, main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run stylelint
